[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_stake = "AZ8gzSPBt1EhogUsV4JTUQpM2hQqaYfxP8eRHDZvCbQ6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
